### ISSUE TITLE
boltdb是如何初始化的？

### ISSUE THREAD

**Issue by ist0ne** [zhangguanzhang/google_containers#3]
boltdb是如何初始化的？如果第一运行，当没有boltdb数据库文件是能不能自动初始化？

**Comment by ist0ne** [comment]
我去掉--db选项，命令是可以运行的，但是没有找到boltdb数据库文件。如果我再次运行sync命令，是不是还会重新同步一次？

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/google_containers/blob/master/cmd/sync.go#L54
默认是当前路径的bolt.db文件的，你在相同目录再次运行会继续上一次的，是根据bolt里存储决定是否同步的

**Comment by ist0ne** [comment]
我也是启动一个docker运行的，运行的时候并没有看到bolt.db文件

**Comment by zhangguanzhang** [comment]
你用docker的话看看workdir的路径下有没有bolt.db文件

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/google_containers/blob/master/core/option.go#L55
